routes/web.php
<?php

use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::group(['middleware' => ['web'], 'namespace' => 'Frontend'], function () {

    Route::post('posts/{post}/comments/', 'CommentController@store')->name('frontend.comments.store');
    Route::get('/', 'PostController@index');
    Route::get('/search', 'PostController@search')->name('frontend.search');
    Route::get('{alias}', 'PostController@onePost')->name('post')->where('alias', '[A-Za-z0-9-]+');
    Route::get('category/{category}', 'CategoryController@index')->name('frontend.categories');
});

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['web'], 'prefix' => 'backend', 'namespace' => 'Backend'], function () {
    Route::resource('users', 'UserController');
});

Route::group(['middleware' => ['web'], 'prefix' => 'backend/roles', 'namespace' => 'Backend'], function () {
    Route::post('/', 'RoleController@store')->name('roles.store');
    Route::get('/', 'RoleController@index')->name('roles.index');
    Route::get('/{id}/edit', 'RoleController@edit');
    Route::get('/create', 'RoleController@create')->name('roles.create');
    Route::patch('/{role}', 'RoleController@update')->name('roles.update');
    Route::delete('/{role}', 'RoleController@destroy')->name('roles.destroy');
    Route::resource('roles', 'RoleController');
});

Route::group(['middleware' => ['web'], 'prefix' => 'backend/permissions', 'namespace' => 'Backend'], function () {
    Route::post('/', 'PermissionController@store')->name('permissions.store');
    Route::get('/', 'PermissionController@index')->name('permissions.index');
    Route::get('/{id}/edit', 'PermissionController@edit');
    Route::get('/create', 'PermissionController@create')->name('permissions.create');
    Route::delete('/{permission}', 'PermissionController@destroy')->name('permissions.destroy');
});

Route::group(['middleware' => ['web'], 'prefix' => 'backend/categories', 'namespace' => 'Backend'], function () {
    Route::post('/', 'CategoryController@store')->name('backend.categories.store');
    Route::get('/', 'CategoryController@index')->name('categories');
    Route::get('/create', 'CategoryController@create')->name('categories.create');
    Route::get('/{category}/edit', 'CategoryController@edit');
    Route::get('/{category}', 'CategoryController@show')->name('categories.show');
    Route::patch('/{category}', 'CategoryController@update')->name('categories.update');
    Route::delete('/{category}', 'CategoryController@destroy')->name('categories.destroy');
});

Route::group(['middleware' => ['web'], 'prefix' => 'backend/posts', 'namespace' => 'Backend'], function () {
    Route::post('/', 'PostController@store')->name('backend.posts.store');
    Route::get('/', 'PostController@index')->name('posts');
    Route::get('/create', 'PostController@create')->name('posts.create');
    Route::get('/{post}/edit', 'PostController@edit');
    Route::get('/{post}', 'PostController@show')->name('posts.show');
    Route::patch('/{post}', 'PostController@update')->name('posts.update');
    Route::delete('/{post}', 'PostController@destroy')->name('posts.destroy');
});

Route::group(['middleware' => ['web'], 'prefix' => 'backend/comments', 'namespace' => 'Backend'], function () {
    Route::post('/', 'CommentController@store')->name('comments.store');
    Route::get('/', 'CommentController@index')->name('comments');
    Route::get('/create', 'CommentController@create')->name('comments.create');
    Route::get('/{comment}/edit', 'CommentController@edit');
    Route::patch('/{comment}', 'CommentController@update')->name('comments.update');
    Route::delete('/{comment}', 'CommentController@destroy')->name('comments.destroy');

});
Route::group(['middleware' => ['web'], 'prefix' => 'backend/avaibility-post', 'namespace' => 'Backend'], function () {
    Route::post('/{id}', 'AvaibilityPostController@published')->name('completed-post.published');
    Route::delete('/{id}', 'AvaibilityPostController@unpublished')->name('completed-post.unpublished');
});

Route::group(['middleware' => ['web'], 'prefix' => 'backend/dashboard', 'namespace' => 'Backend'], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');
});
//
//Route::get('/create_role_permission', function (){
//    $role = Role::create(['name' => 'Administer']);
//    $permission = Permission::create(['name' => 'Administer roles & permissions']);
//    auth()->user()->assignRole('Administer');
//    auth()->user()->givePermissionTo('Administer roles & permissions');
//});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Auth;
use Spatie\Permission\Exceptions\GuardDoesNotMatch;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function isAdmin()
    {
        return Auth::user()->hasRole('Administer');
    }

    public function isModerator()
    {
        return Auth::user()->hasRole('Moderator');
    }
}

app/Http/Controllers/Backend/UserController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use Auth;

//Importing laravel-permission models
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

//Enables us to output flash messaging
use Session;

class UserController extends Controller {

    public function __construct() {
        $this->middleware(['auth', 'isAdmin']); //isAdmin middleware lets only users with a //specific permission permission to access these resources
    }

    public function index() {
        //Get all users and pass it to the view
        $users = User::all();
        return view('users.index')->with('users', $users);
    }

    public function create() {
        //Get all roles and pass it to the view
        $roles = Role::get();
        return view('users.create', ['roles'=>$roles]);
    }


    public function store(Request $request) {
        //Validate name, email and password fields
        $this->validate($request, [
            'name'=>'required|max:120',
            'email'=>'required|email|unique:users',
            'password'=>'required|min:6|confirmed'
        ]);

        $user = User::create($request->only('email', 'name', 'password')); //Retrieving only the email and password data

        $roles = $request['roles']; //Retrieving the roles field
        //Checking if a role was selected
        if (isset($roles)) {

            foreach ($roles as $role) {
                $role_r = Role::where('id', '=', $role)->firstOrFail();
                $user->assignRole($role_r); //Assigning role to user
            }
        }
        //Redirect to the users.index view and display message
        return redirect()->route('users.index')
            ->with('flash_message',
                'User successfully added.');
    }


    public function show($id) {
        return redirect('users');
    }


    public function edit($id) {
        $user = User::findOrFail($id); //Get user with specified id
        $roles = Role::get(); //Get all roles

        $checked = $user->roles()->pluck('role_id')->first() ? true : false;

        return view('users.edit', compact('user', 'roles', 'checked')); //pass user and roles data to view
    }


    public function update(Request $request, $id) {
        $user = User::findOrFail($id); //Get role specified by id

        //Validate name, email and password fields
        $this->validate($request, [
            'name'=>'required|max:120',
            'email'=>'required|email|unique:users,email,'.$id,
            'password'=>'required|min:6|confirmed'
        ]);
        $input = $request->only(['name', 'email', 'password']); //Retreive the name, email and password fields
        $roles = $request['roles']; //Retreive all roles
        $user->fill($input)->save();

        if (isset($roles)) {
            $user->roles()->sync($roles);  //If one or more role is selected associate user to roles
        }
        else {
            $user->roles()->detach(); //If no role is selected remove exisiting role associated to a user
        }
        return redirect()->route('users.index')
            ->with('flash_message',
                'User successfully edited.');
    }


    public function destroy($id) {
        //Find a user with a given id and delete
        $user = User::findOrFail($id);
        $user->delete();

        return redirect()->route('users.index')
            ->with('flash_message',
                'User successfully deleted.');
    }
}

resources/views/users/create.blade.php
@extends('layouts.backend.app')

@section('title', '| Add User')

@section('content')

    <div class='col-lg-4 col-lg-offset-4'>

        <h1><i class='fa fa-user-plus'></i> Add User</h1>
        <hr>

        <form action="{{route('users.store')}}" method="POST">
            @csrf
{{--        {{ Form::open(array('url' => 'users')) }}--}}

        <div class="form-group">
            <input type="text" class="input form-control {{$errors->has('name') ? 'is-danger' : ''}}" name="name"  value="{{old('name')}}">
{{--            {{ Form::label('name', 'Name') }}--}}
{{--            {{ Form::text('name', '', array('class' => 'form-control')) }}--}}
        </div>

        <div class="form-group">
            <input type="text" class="input form-control {{$errors->has('email') ? 'is-danger' : ''}}" name="email"  value="{{old('email')}}">
{{--            {{ Form::label('email', 'Email') }}--}}
{{--            {{ Form::email('email', '', array('class' => 'form-control')) }}--}}
        </div>

        <div class='form-group'>
            <div class="form-group">
                @foreach ($roles as $role)
                <div class="form-check">
                    <label class="az-content-label">{{$role->name}}</label>
                    <input class="form-check-input" type="checkbox" name="roles[]" value="{{$role->id}}">
                </div>
                @endforeach
            </div>


{{--            @foreach ($roles as $role)--}}
{{--                {{ Form::checkbox('roles[]',  $role->id ) }}--}}
{{--                {{ Form::label($role->name, ucfirst($role->name)) }}<br>--}}

{{--            @endforeach--}}
        </div>

        <div class="form-group">
            <label class="az-content-label">Password</label>
            <input type="text" class="input form-control {{$errors->has('password') ? 'is-danger' : ''}}" name="password"  value="{{old('password')}}">

{{--            {{ Form::label('password', 'Password') }}<br>--}}
{{--            {{ Form::password('password', array('class' => 'form-control')) }}--}}

        </div>

        <div class="form-group">
            <label class="az-content-label">Confirm Password'</label>
            <input type="text" class="input form-control {{$errors->has('password_confirmation') ? 'is-danger' : ''}}" name="password_confirmation"  value="{{old('password_confirmation')}}">
{{--            {{ Form::label('password', 'Confirm Password') }}<br>--}}
{{--            {{ Form::password('password_confirmation', array('class' => 'form-control')) }}--}}

        </div>

            <button type="submit" class="btn btn-primary">Add</button>
{{--        {{ Form::submit('Add', array('class' => 'btn btn-primary')) }}--}}

{{--        {{ Form::close() }}--}}
        </form>
    </div>

@endsection

resources/views/users/edit.blade.php
@extends('layouts.backend.app')

@section('title', '| Edit User')

@section('content')

    <div class='col-lg-4 col-lg-offset-4'>

        <h1><i class='fa fa-user-plus'></i> Edit {{$user->name}}</h1>
        <hr>
        <form action="{{route('users.update', $user->id )}}" method="POST">
            @method('PATCH')
            @csrf

        <div class="form-group">

            <div class="form-group">
                <label class="az-content-label">Name</label>
                <input type="text" class="input form-control {{$errors->has('name') ? 'is-danger' : ''}}" name="name"  value="{{$user->name}}">
            </div>
        </div>

        <div class="form-group">

            <div class="form-group">
                <label class="az-content-label">Email</label>
                <input type="text" class="input form-control {{$errors->has('email') ? 'is-danger' : ''}}" name="email"  value="{{$user->email}}">
            </div>
        </div>

        <h5><b>Give Role</b></h5>

        <div class='form-group'>

                @foreach ($roles as $role)
                    <div class="form-check">
                        <label class="az-content-label">{{$role->name}} </label>
                        <input class="form-check-input" type="checkbox" name="roles[]" value="{{$role->id}}" {{$checked ? 'checked' : '' }}>
                    </div>
                @endforeach

        </div>

            <div class="form-group">
                <label class="az-content-label">Password</label>
                <input type="text" class="input form-control {{$errors->has('password') ? 'is-danger' : ''}}" name="password"  value="{{$user->password}}">
            </div>



            <div class="form-group">
                <label class="az-content-label">Confirm Password'</label>
                <input type="text" class="input form-control {{$errors->has('password_confirmation') ? 'is-danger' : ''}}" name="password_confirmation"  value="{{$user->password_confirmation}}">
            </div>
            <button type="submit" class="btn btn-primary">Add</button>

        </form>

    </div>

@endsection

resources/views/users/index.blade.php
@extends('layouts.backend.app')

@section('title', '| Users')

@section('content')
    @include('success')
    <div class="col-lg-10 col-lg-offset-1">
        <h1><i class="fa fa-users"></i> User Administration <a href="{{ route('roles.index') }}" class="btn btn-default pull-right">Roles</a>
            <a href="{{ route('permissions.index') }}" class="btn btn-default pull-right">Permissions</a></h1>
        <hr>
        <div class="table-responsive">
            <table class="table table-bordered table-striped">

                <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Date/Time Added</th>
                    <th>User Roles</th>
                    <th>Operations</th>
                </tr>
                </thead>

                <tbody>
                @foreach ($users as $user)
                    <tr>

                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->created_at->format('F d, Y h:ia') }}</td>
                        <td>{{  $user->roles()->pluck('name')->implode(' ') }}</td>{{-- Retrieve array of roles associated to a user and convert to string --}}
                        <td>
                            <a href="{{ route('users.edit', $user->id) }}" class="btn btn-info pull-left" style="margin-right: 3px;">Edit</a>

                            <form action="{{route('users.destroy', $user->id)}}" method="POST">
                                @method('DELETE')
                                @csrf
                                <button type="submit" onclick="return confirm('Are you sure you want to delete this Post?');" class="btn btn-danger"><i class="material-icons"></i> <span>Delete</span></button>

                            </form>

{{--                            --}}
{{--                            {!! Form::open(['method' => 'DELETE', 'route' => ['users.destroy', $user->id] ]) !!}--}}
{{--                            {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}--}}
{{--                            {!! Form::close() !!}--}}

                        </td>
                    </tr>
                @endforeach
                </tbody>

            </table>
        </div>

        <a href="{{ route('users.create') }}" class="btn btn-success">Add User</a>

    </div>

@endsection