routes/web.php
<?php

use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::group(['middleware' => ['web'], 'namespace' => 'Frontend'], function () {

    Route::post('posts/{post}/comments/', 'CommentController@store')->name('frontend.comments.store');
    Route::get('/', 'PostController@index');
    Route::get('/search', 'PostController@search')->name('frontend.search');
    Route::get('{alias}', 'PostController@onePost')->name('post')->where('alias', '[A-Za-z0-9-]+');
    Route::get('category/{category}', 'CategoryController@index')->name('frontend.categories');
});

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['web'], 'prefix' => 'backend', 'namespace' => 'Backend'], function () {
    Route::resource('users', 'UserController');
});

Route::group(['middleware' => ['web'], 'prefix' => 'backend/roles', 'namespace' => 'Backend'], function () {
    Route::post('/', 'RoleController@store')->name('roles.store');
    Route::get('/', 'RoleController@index')->name('roles.index');
    Route::get('/{id}/edit', 'RoleController@edit');
    Route::get('/create', 'RoleController@create')->name('roles.create');
    Route::patch('/{role}', 'RoleController@update')->name('roles.update');
    Route::delete('/{role}', 'RoleController@destroy')->name('roles.destroy');
    Route::resource('roles', 'RoleController');
});

Route::group(['middleware' => ['web'], 'prefix' => 'backend/permissions', 'namespace' => 'Backend'], function () {
    Route::post('/', 'PermissionController@store')->name('permissions.store');
    Route::get('/', 'PermissionController@index')->name('permissions.index');
    Route::get('/{id}/edit', 'PermissionController@edit');
    Route::get('/create', 'PermissionController@create')->name('permissions.create');
    Route::delete('/{permission}', 'PermissionController@destroy')->name('permissions.destroy');
});

Route::group(['middleware' => ['web'], 'prefix' => 'backend/categories', 'namespace' => 'Backend'], function () {
    Route::post('/', 'CategoryController@store')->name('backend.categories.store');
    Route::get('/', 'CategoryController@index')->name('categories');
    Route::get('/create', 'CategoryController@create')->name('categories.create');
    Route::get('/{category}/edit', 'CategoryController@edit');
    Route::get('/{category}', 'CategoryController@show')->name('categories.show');
    Route::patch('/{category}', 'CategoryController@update')->name('categories.update');
    Route::delete('/{category}', 'CategoryController@destroy')->name('categories.destroy');
});

Route::group(['middleware' => ['web'], 'prefix' => 'backend/posts', 'namespace' => 'Backend'], function () {
    Route::post('/', 'PostController@store')->name('backend.posts.store');
    Route::get('/', 'PostController@index')->name('posts');
    Route::get('/create', 'PostController@create')->name('posts.create');
    Route::get('/{post}/edit', 'PostController@edit');
    Route::get('/{post}', 'PostController@show')->name('posts.show');
    Route::patch('/{post}', 'PostController@update')->name('posts.update');
    Route::delete('/{post}', 'PostController@destroy')->name('posts.destroy');
});

Route::group(['middleware' => ['web'], 'prefix' => 'backend/comments', 'namespace' => 'Backend'], function () {
    Route::post('/', 'CommentController@store')->name('comments.store');
    Route::get('/', 'CommentController@index')->name('comments');
    Route::get('/create', 'CommentController@create')->name('comments.create');
    Route::get('/{comment}/edit', 'CommentController@edit');
    Route::patch('/{comment}', 'CommentController@update')->name('comments.update');
    Route::delete('/{comment}', 'CommentController@destroy')->name('comments.destroy');

});
Route::group(['middleware' => ['web'], 'prefix' => 'backend/avaibility-post', 'namespace' => 'Backend'], function () {
    Route::post('/{id}', 'AvaibilityPostController@published')->name('completed-post.published');
    Route::delete('/{id}', 'AvaibilityPostController@unpublished')->name('completed-post.unpublished');
});

Route::group(['middleware' => ['web'], 'prefix' => 'backend/dashboard', 'namespace' => 'Backend'], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');
});
//
//Route::get('/create_role_permission', function (){
//    $role = Role::create(['name' => 'Administer']);
//    $permission = Permission::create(['name' => 'Administer roles & permissions']);
//    auth()->user()->assignRole('Administer');
//    auth()->user()->givePermissionTo('Administer roles & permissions');
//});

app/Http/Controllers/Backend/AvaibilityPostController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Post;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AvaibilityPostController extends Controller
{
    public function published(Post $post)
    {
        $post->complete($post->id);
        return back()->with('success', "Post $post->id is published successfully");
    }

    public function unpublished(Post $post)
    {
        $post->incomplete($post->id);
        return back()->with('success', "Post $post->id is successfully unpublished");
    }
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Requests\Backend\Categories\FieldRequestCreate;
use App\Http\Requests\Backend\Categories\FieldRequestUpdate;
use App\Models\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;

class CategoryController extends Controller
{
    protected $prefix = 'backend.categories';
    protected $prefixRedirect = 'backend/categories';

    public function index()
    {
        $categories = Category::paginate(10);
        return view($this->prefix.'.index', ['categories' => $categories]);
    }


    public function create()
    {
       return view($this->prefix.'.create');
    }


    public function store(FieldRequestCreate $request)
    {
        Category::create($request->validated());
        return redirect($this->prefixRedirect)->with('success', 'Category "'. $request->name . '" is successfully create');
    }


    public function show(Category $category)
    {
        return view($this->prefix.'.show', ['category' => $category]);
    }


    public function edit(Category $category)
    {
        return view($this->prefix.'.edit', ['category' => $category]);
    }


    public function update(FieldRequestUpdate $request, Category $category)
    {
        $category->update($request->all());
        return redirect($this->prefixRedirect)->with('success', 'Category "'. $request->name . '" is successfully updated');
    }


    public function destroy(Category $category)
    {
        $category->delete();

        return redirect($this->prefixRedirect)->with('success', 'Category "'. $category->name . '" is successfully deleted');
    }
}

app/Http/Controllers/Backend/CommentController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Helpers\ImageHelper;
use App\Http\Requests\Backend\Comments\FieldRequestCreate;
use App\Http\Requests\Backend\Comments\FieldRequestUpdate;
use App\Models\Comment;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;

class CommentController extends Controller
{
    protected $prefix = 'backend.comments';
    protected $prefixRedirect = 'backend/comments';


    public function index()
    {
        $comments = Comment::paginate(10);

        return view($this->prefix.'.index', ['comments' => $comments]);
    }


    public function create()
    {
        return view($this->prefix.'.create');
    }


    public function store(FieldRequestCreate $request, Comment $comment)
    {
        $comment->body = $request->body;
        $comment->is_published = (boolean) $request->is_published;
        $comment->post_id = $request->post_id;
        $comment->user_name = $request->user_name;
        $comment->user_email = $request->user_email;

        $imageName = null;
        if ($request->has('image')) {
            $imageName = $this->galleryUpload($request)['file_name'];
        }
        $comment->image = $imageName;
        $comment->save();
        return redirect($this->prefixRedirect)->with('success', 'Comment is successfully create');

    }

    public function galleryUpload($request)
    {
        $name = ImageHelper::generateName(Comment::GALLERY_PATH, $request->file('image'));
        $image = Storage::disk('public')->putFileAs(Comment::GALLERY_PATH, $request->file('image'), $name);
        return [
            'file'      => Storage::url($image),
            'file_name' => $name,
        ];
    }
    public function edit(Comment $comment)
    {
        return view($this->prefix.'.edit', ['comment' => $comment]);
    }

    public function update(FieldRequestUpdate $request, Comment $comment)
    {
        $requestData = $request->all();
        $requestData['is_published'] = $request->has('is_published') ? true : false;

        if ($request->has('image')) {
            $requestData['image'] = $this->galleryUpload($request)['file_name'];
        }

        $comment->update($requestData);

        return redirect($this->prefixRedirect)->with('success',  'Id ' .$comment->id . ' is successfully updated');
    }


    public function destroy(Comment $comment)
    {
        $comment->delete();
        return redirect($this->prefixRedirect)->with('success', 'Comment №"'. $comment->id . '" is successfully deleted');
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php
namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Post;
use App\Models\Comment;

class DashboardController extends Controller
{

    protected $prefix = 'backend.dashboard';
    protected $prefixRedirect = 'backend/dashboard';

    public function index()
    {

        $comments = Comment::count();
        $commentsDisabled  = Comment::whereIsPublished(false)->count();
        $commentsActive   = Comment::whereIsPublished(true)->count();

        $posts = Post::count();
        $postsDisabled = Post::whereIsPublished(false)->count();
        $postsActive = Post::whereIsPublished(true)->count();

        $categories = Category::count();

        return view($this->prefix.'.index', [
            'posts' => $posts,
            'postsDisabled'=> $postsDisabled,
            'postsActive' => $postsActive,
            'comments' => $comments,
            'commentsDisabled' => $commentsDisabled,
            'commentsActive' => $commentsActive,
            'categories' => $categories
        ]);
    }
}

app/Http/Controllers/Backend/PermissionController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;

//Importing laravel-permission models
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

use Session;

class PermissionController extends Controller
{

    protected $prefixRedirect = 'backend/permissions';

    public function __construct() {
        $this->middleware(['auth', 'isAdmin']); //isAdmin middleware lets only users with a //specific permission permission to access these resources
    }


    public function index() {
        $permissions = Permission::all(); //Get all permissions

        return view('permissions.index')->with('permissions', $permissions);
    }


    public function create() {
        $roles = Role::get(); //Get all roles

        return view('permissions.create')->with('roles', $roles);
    }


    public function store(Request $request) {
        $this->validate($request, [
            'name'=>'required|max:40',
        ]);

        $name = $request['name'];
        $permission = new Permission();
        $permission->name = $name;

        $roles = $request['roles'];

        $permission->save();

        if (!empty($request['roles'])) { //If one or more role is selected
            foreach ($roles as $role) {
                $r = Role::where('id', '=', $role)->firstOrFail(); //Match input role to db record

                $permission = Permission::where('name', '=', $name)->first(); //Match input //permission to db record
                $r->givePermissionTo($permission);
            }
        }

        return redirect($this->prefixRedirect)->with('success', 'Permission '. $permission->name.' is successfully create');
    }


    public function show($id) {
        return redirect('permissions');
    }

    public function edit($id) {
        $permission = Permission::findOrFail($id);

        return view('permissions.edit', compact('permission'));
    }

    public function update(Request $request, $id) {
        $permission = Permission::findOrFail($id);
        $this->validate($request, [
            'name'=>'required|max:40',
        ]);
        $permission->fill($request->all())
            ->save();

        return redirect($this->prefixRedirect)->with('success',   'Permission '. $permission->name.' is successfully updated');
    }


    public function destroy(Permission $permission) {

        $this->authorize('delete', $permission);

        $permission->delete();

        return redirect($this->prefixRedirect)->with('success', 'Permission "'. $permission->name . '" is successfully deleted');
    }
}

app/Http/Controllers/Backend/PostController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Helpers\ImageHelper;
use App\Http\Requests\Backend\Posts\FieldRequestCreate;
use App\Http\Requests\Backend\Posts\FieldRequestUpdate;
use App\Http\Requests\Posts\UploadImageRequest;
use App\Models\Category;
use App\Models\Post;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Traits\UploadTrait;
use Illuminate\Support\Facades\Storage;
use Cocur\Slugify\Slugify;
use Illuminate\Support\Facades\Validator;

class PostController extends Controller
{
    use UploadTrait;

    protected $prefix = 'backend.posts';
    protected $prefixRedirect = 'backend/posts';

    public function __construct() {
        $this->middleware(['auth', 'clearance'])->except('index', 'show');
    }

    public function index()
    {
        $posts = Post::paginate(10);
        return view($this->prefix.'.index', ['posts' => $posts]);
    }


    public function create()
    {
        $categories = Category::select('id', 'name')->get();

        return view($this->prefix.'.create', ['categories' => $categories]);
    }


    public function store(FieldRequestCreate $request, Post $post)
    {
        $post  = new Post($request->all());
//        $post->fill($request->all());
        $post->alias = $this->createAlias($request);
        $imageName = null;
        if ($request->has('image')) {
          $imageName = $this->galleryUpload($request)['file_name'];
        }
        $post->image = $imageName;

        $post->save();
        return redirect($this->prefixRedirect)->with('success', 'Post is successfully create');
    }

    public function createAlias($request)
    {
        $slugify = new Slugify();

        if (is_null($request->alias)) {
            return $slugify->slugify($request->title);
        }

        return $request->alias;
    }

    public function galleryUpload($request)
    {
        $name = ImageHelper::generateName(Post::GALLERY_PATH, $request->file('image'));
        $image = Storage::disk('public')->putFileAs(Post::GALLERY_PATH, $request->file('image'), $name);
        return [
            'file'      => Storage::url($image),
            'file_name' => $name,
        ];
    }


    public function show(Post $post)
    {
        $categories = Category::select('id', 'name')->get();

        return view($this->prefix.'.'.__FUNCTION__, ['post' => $post, 'categories' => $categories]);
    }


    public function edit(Post $post)
    {

        $categories = Category::select('id', 'name')->get();

        return view($this->prefix.'.edit', ['post' => $post, 'categories' => $categories]);
    }


    public function update(FieldRequestUpdate $request, Post $post)
    {

        $this->authorize('update', $post);

        $requestData = $request->all();
        $requestData['is_published'] = $request->has('is_published');

        if ($request->has('image')) {
            $requestData['image'] = $this->galleryUpload($request)['file_name'];
        }

        $post->update($requestData);

        return redirect($this->prefixRedirect)->with('success',  $request->title . ' is successfully updated');
    }


    public function destroy(Post $post)
    {
        $post->delete();
        return redirect($this->prefixRedirect)->with('success', 'Post №"'. $post->id . '" is successfully deleted');
    }
}

resources/views/layouts/backend/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="{{ asset('js/custom.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.css">
    <link rel="stylesheet" href="https://getbootstrap.com/docs/4.3/examples/dashboard/dashboard.css">

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/custom.css') }}" rel="stylesheet">

</head>
<body>
    <div id="app">
        <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
            <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="/">Blog</a>

            <ul class="navbar-nav px-3">
                <!-- Authentication Links -->
                <li class="nav-item dropdown">
                    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                        {{ Auth::user()->name }} <span class="caret"></span>
                    </a>

                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{{ route('logout') }}"
                           onclick="event.preventDefault();
                               document.getElementById('logout-form').submit();">
                            {{ __('Logout') }}
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </div>
                </li>
            </ul>
        </nav>
        <div class="container-fluid">
            <div class="row">
                <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                    <div class="sidebar-sticky">
                        <ul class="nav flex-column">
                            @role('Administer')
                                <li class="nav-item">
                                    <a class="nav-link {!!PageHelper::setActive('backend/roles')!!}" href="{{route('roles.index')}}">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                                        Manage Roles
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link {!!PageHelper::setActive('backend/permissions')!!}" href="{{route('permissions.index')}}">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                                        Manage Permissions
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link {!!PageHelper::setActive('backend/users/create')!!}" href="{{route('users.create')}}">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                                        Create User
                                    </a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link {!!PageHelper::setActive('backend/users')!!}" href="{{route('users.index')}}">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                                        User List
                                    </a>
                                </li>
                            @endrole
                            <li class="nav-item">
                                <a class="nav-link {!!PageHelper::setActive('backend/dashboard')!!}" href="{{route('dashboard')}}">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                                    Dashboard <span class="sr-only">(current)</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {!!PageHelper::setActive('backend/posts')!!}" href="{{ route('posts') }}">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path><polyline points="13 2 13 9 20 9"></polyline></svg>
                                    Posts
                                </a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link {!!PageHelper::setActive('backend/comments')!!}" href="{{ route('comments') }}">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
                                    Comments
                                </a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link {!!PageHelper::setActive('backend/categories')!!}" href="{{ route('categories') }}">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-layers"><polygon points="12 2 2 7 12 12 22 7 12 2"></polygon><polyline points="2 17 12 22 22 17"></polyline><polyline points="2 12 12 17 22 12"></polyline></svg>
                                    Categories
                                </a>
                            </li>
                        </ul>
                    </div>
                </nav>

                <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
                        @yield('content')
                </main>
            </div>
        </div>
    </div>
</body>
</html>